[phases.setup] 
nixPkgs = ['python311', 'pip', 'ffmpeg'] 
 
[phases.install] 
cmds = ['pip install -r requirements.txt'] 
 
[start] 
cmd = 'uvicorn clean_news_automation:app --host 0.0.0.0 --port $PORT' 
