[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
RAILWAY = "true"
ENVIRONMENT = "production"